# Generated by Django 4.2.4 on 2023-09-03 23:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabApp',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('user_type_id', models.SmallIntegerField(max_length=2)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.SmallIntegerField(max_length=2)),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True)),
                ('phone', models.IntegerField(max_length=14)),
            ],
        ),
    ]
