# Generated by Django 4.2.4 on 2023-09-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labapp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='labapp',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='labapp',
            name='user_type_id',
            field=models.SmallIntegerField(),
        ),
    ]
