# Generated by Django 4.2.4 on 2023-09-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0002_alter_labapp_is_active_alter_labapp_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labapp',
            name='is_active',
            field=models.SmallIntegerField(choices=[(0, 'Ativo'), (1, 'Inativo')], default=1),
        ),
        migrations.AlterField(
            model_name='labapp',
            name='user_type_id',
            field=models.SmallIntegerField(choices=[(0, 'Admin'), (1, 'Usuario')], default=1),
        ),
    ]
